export const SET_SUBREDDIT_FULLFILED = "SET_SUBREDDIT_FULLFILED";
export const SET_SUBREDDIT = "SET_SUBREDDIT";
export const FETCH_SUBREDDIT = "FETCH_SUBREDDIT";
export const FETCH_SUBREDDIT_FULLFILLED ="FETCH_SUBREDDIT_FULLFILLED";
export const SET_AFTER_KEY = "SET_AFTER_KEY";
export const FETCH_SUBREDDIT_REJECTED = "FETCH_SUBREDDIT_REJECTED";
export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_FULLFILLED ="FETCH_POST_FULLFILLED";
export const FETCH_MORE_POSTS = "FETCH_MORE_POSTS";
export const FETCH_MORE_POSTS_FULLFILLED = "FETCH_MORE_POSTS_FULLFILLED";
export const COUNTER  = "COUNTER"; //HARDCODED COUNTER
export const ADD_COMMENT = "ADD_COMMENT" //HARDCODED ENDPOINT
export const COMMENT_BODY = "COMMENT_BODY" //COMMENT BODY

