export const CURRENT_SUBREDDIT = "CURRENT_SUBREDDIT";
export const SET_SUBREDDIT = "SET_SUBREDDIT";
export const FETCH_SUBREDDIT = "FETCH_SUBREDDIT";
export const FETCH_SUBREDDIT_FULLFILLED ="FETCH_SUBREDDIT_FULLFILLED";
export const SET_AFTER_KEY = "SET_AFTER_KEY";

