export const SET_SUBREDDIT_FULLFILED = "SET_SUBREDDIT_FULLFILED";
export const SET_SUBREDDIT = "SET_SUBREDDIT";
export const FETCH_SUBREDDIT = "FETCH_SUBREDDIT";
export const FETCH_SUBREDDIT_FULLFILLED ="FETCH_SUBREDDIT_FULLFILLED";
export const SET_AFTER_KEY = "SET_AFTER_KEY";
export const FETCH_SUBREDDIT_REJECTED = "FETCH_SUBREDDIT_REJECTED";

